mail_server: smtp.gmail.com
mail_use_ssl: true
mail_ssl_port: 465
mail_use_tls: true
mail_tls_port: 587
mail_username: flaskdevacc@gmail.com
mail_password: M1litary4463
mail_sender_address: flaskdevacc@gmail.com
postgres_username: postgres
postgres_password: postgres