"""empty message

Revision ID: 09520b1aa6cb
Revises: 41f4b277eb7d
Create Date: 2017-06-17 20:25:19.448553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09520b1aa6cb'
down_revision = '41f4b277eb7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('psot_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'posts', ['psot_id'], ['id'])
    op.add_column('posts', sa.Column('sub_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'subs', ['sub_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'sub_id')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'psot_id')
    # ### end Alembic commands ###
