"""empty message

Revision ID: 338bfa9566b5
Revises: cac80feaf49d
Create Date: 2018-02-23 16:43:36.003176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '338bfa9566b5'
down_revision = 'cac80feaf49d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('timeformat', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'timeformat')
    # ### end Alembic commands ###
