"""empty message

Revision ID: 44bd6b86fec8
Revises: 1497b29b636d
Create Date: 2017-06-17 20:29:50.611214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44bd6b86fec8'
down_revision = '1497b29b636d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('author', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'users', ['author'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'author')
    # ### end Alembic commands ###
