"""empty message

Revision ID: 51db71b7b7e5
Revises: 3401f6788484
Create Date: 2018-01-13 08:28:17.415787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51db71b7b7e5'
down_revision = '3401f6788484'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('use_icons', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'use_icons')
    # ### end Alembic commands ###
