"""empty message

Revision ID: 62c8b4500d2d
Revises: e7230e1093af
Create Date: 2018-02-24 23:03:32.747943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62c8b4500d2d'
down_revision = 'e7230e1093af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('modified', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'modified')
    # ### end Alembic commands ###
