"""empty message

Revision ID: 7ee8eb02038e
Revises: 977d0edb0f8d
Create Date: 2017-12-14 16:06:23.285245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ee8eb02038e'
down_revision = '977d0edb0f8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('registered_on', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'registered_on')
    # ### end Alembic commands ###
