"""empty message

Revision ID: 977d0edb0f8d
Revises: b9ce3b6c7e7c
Create Date: 2017-12-14 16:04:47.720838

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '977d0edb0f8d'
down_revision = 'b9ce3b6c7e7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.drop_column('users', 'is_confirmed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_confirmed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
