"""empty message

Revision ID: a1f7c0b8cdc5
Revises: 44bd6b86fec8
Create Date: 2017-06-17 21:08:27.216115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1f7c0b8cdc5'
down_revision = '44bd6b86fec8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subs', sa.Column('url', sa.String(length=8), nullable=True))
    op.create_unique_constraint(None, 'subs', ['url'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subs', type_='unique')
    op.drop_column('subs', 'url')
    # ### end Alembic commands ###
