"""empty message

Revision ID: d12d430b5532
Revises: 7ee8eb02038e
Create Date: 2017-12-14 19:02:21.043020

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd12d430b5532'
down_revision = '7ee8eb02038e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.String(length=64), nullable=True))
    op.drop_index('name', table_name='posts')
    op.create_unique_constraint(None, 'posts', ['title'])
    op.drop_column('posts', 'name')
    op.drop_column('posts', 'description')
    op.add_column('subs', sa.Column('pinned', sa.Boolean(), nullable=True))
    op.add_column('subs', sa.Column('title', sa.String(length=64), nullable=True))
    op.drop_index('name', table_name='subs')
    op.create_unique_constraint(None, 'subs', ['title'])
    op.drop_column('subs', 'name')
    op.drop_column('subs', 'is_pinned')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subs', sa.Column('is_pinned', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('subs', sa.Column('name', mysql.VARCHAR(length=64), nullable=True))
    op.drop_constraint(None, 'subs', type_='unique')
    op.create_index('name', 'subs', ['name'], unique=True)
    op.drop_column('subs', 'title')
    op.drop_column('subs', 'pinned')
    op.add_column('posts', sa.Column('description', mysql.VARCHAR(length=192), nullable=True))
    op.add_column('posts', sa.Column('name', mysql.VARCHAR(length=64), nullable=True))
    op.drop_constraint(None, 'posts', type_='unique')
    op.create_index('name', 'posts', ['name'], unique=True)
    op.drop_column('posts', 'title')
    # ### end Alembic commands ###
