"""empty message

Revision ID: d376c01d8b30
Revises: 51db71b7b7e5
Create Date: 2018-01-13 08:34:59.301461

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd376c01d8b30'
down_revision = '51db71b7b7e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'edited',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('messages', 'is_read',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('subs', 'pinned',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('users', 'confirmed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('users', 'is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('users', 'use_icons',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'use_icons',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('users', 'is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('users', 'confirmed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('subs', 'pinned',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('messages', 'is_read',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('comments', 'edited',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    # ### end Alembic commands ###
